ngo_explorer/blueprints/data.py
from typing import Optional

from flask import Blueprint, Response, jsonify, render_template, request, url_for
from flask_babel import _

from ngo_explorer.classes.charity import Charity
from ngo_explorer.classes.countries import (
    CountryGroupItem,
    CountryGroupItemList,
    CountryGroupItemUpload,
)
from ngo_explorer.utils.countries import (
    get_country_groups_lists,
    get_multiple_countries,
)
from ngo_explorer.utils.download import download_file
from ngo_explorer.utils.fetchdata import (
    fetch_all_charities,
    fetch_charity_details,
    fetch_iati,
    fetch_iati_by_charity,
)
from ngo_explorer.utils.filters import parse_filters

SUBPAGES = ["dashboard", "show-charities", "download"]

bp: Blueprint = Blueprint("data", __name__, url_prefix="/")


@bp.route(
    "/region/<regiontype>/<regionid>/<subpage>.<filetype>", methods=["GET", "POST"]
)
@bp.route("/region/<regiontype>/<regionid>.<filetype>", methods=["GET", "POST"])
@bp.route("/region/<regiontype>/<regionid>/<subpage>")
@bp.route("/region/<regiontype>/<regionid>")
def region(
    regionid: str,
    regiontype: str = "continent",
    filetype: str = "html",
    subpage: str = "dashboard",
) -> tuple[str, int] | str | Response:
    if subpage not in SUBPAGES:
        return render_template("404.html.j2"), 404

    area = get_country_groups_lists().get((regiontype, regionid))

    if not area:
        return (
            render_template(
                "404.html.j2",
                lookingfor=_(
                    '%(regiontype)s "%(regionid)s" could not be found',
                    regiontype=regiontype,
                    regionid=regionid,
                ),
            ),
            404,
        )

    return data_page(
        area,
        filetype=filetype,
        page=subpage,
        url_base=[".region", {"regiontype": regiontype, "regionid": regionid}],
    )


@bp.route("/country/<countryid>/<subpage>.<filetype>", methods=["GET", "POST"])
@bp.route("/country/<countryid>.<filetype>", methods=["GET", "POST"])
@bp.route("/country/<countryid>/<subpage>")
@bp.route("/country/<countryid>")
def country(
    countryid: str, filetype: str = "html", subpage: str = "dashboard"
) -> tuple[str, int] | str | Response:
    if subpage not in SUBPAGES:
        return render_template("404.html.j2"), 404

    area = get_multiple_countries(countryid)

    if not area:
        return (
            render_template(
                "404.html.j2",
                lookingfor=_(
                    'Country "%(countryid)s" could not be found', countryid=countryid
                ),
            ),
            404,
        )

    return data_page(
        area,
        filetype=filetype,
        page=subpage,
        url_base=[".country", {"countryid": countryid}],
    )


def data_page(
    area: Optional[
        CountryGroupItem | CountryGroupItemList | CountryGroupItemUpload
    ] = None,
    charity_ids: Optional[list[str]] = None,
    filetype: str = "html",
    page: str = "dashboard",
    url_base=[],
) -> tuple[str, int] | str | Response:
    if request.method == "POST":
        filters_raw = request.form
    else:
        filters_raw = request.args
    filters_url = {
        k: v if k in ["filter-countries", "filter-classification"] else v[0]
        for k, v in filters_raw.lists()
        if v != [""]
    }

    pages = {
        "dashboard": {
            "name": _("Dashboard"),
            "template": "data.html.j2",
            "url": url_for(url_base[0], **{**url_base[1], **filters_url}),
            "api_url": url_for(
                url_base[0], **{**url_base[1], **filters_url, "filetype": "json"}
            ),
        },
        "show-charities": {
            "name": _("Show NGOs"),
            "template": "data-show-charities.html.j2",
            "url": url_for(
                url_base[0],
                **{**url_base[1], **filters_url, "subpage": "show-charities"},
            ),
            "api_url": url_for(
                url_base[0],
                **{
                    **url_base[1],
                    **filters_url,
                    "subpage": "show-charities",
                    "filetype": "json",
                },
            ),
        },
        "download": {
            "name": _("Download"),
            "template": "data-download.html.j2",
            "url": url_for(
                url_base[0], **{**url_base[1], **filters_url, "subpage": "download"}
            ),
            "api_url": url_for(
                url_base[0],
                **{
                    **url_base[1],
                    **filters_url,
                    "subpage": "download",
                    "filetype": "json",
                },
            ),
        },
    }
    qgl_query = "charity_aggregation" if page == "dashboard" else "charity_list"

    filters = parse_filters(filters_raw)

    download_type = request.values.get("download_type")
    if download_type:
        return download_file(
            area=area,
            ids=charity_ids,
            filters=filters,
            fields=request.values.getlist("fields"),
            filetype=download_type.lower(),
        )

    fetch_countries = None
    fetch_ids = None
    if area and area.countries:
        fetch_countries = area.countries
    if charity_ids:
        fetch_ids = charity_ids

    charity_data = fetch_charity_details(
        filters=filters,
        limit=30,
        skip=getattr(filters, "skip", 0),
        query=qgl_query,
        sort="random" if page == "dashboard" else "default",
        countries=fetch_countries,
        ids=fetch_ids,
    )
    charity_data.set_charts()

    iati_data = None
    if area and area.countries:
        for country in area.countries:
            # whether the country has been filtered to the
            country.filtered = (
                country.id in filters.countries if filters.countries else True
            )
            # number of charities in the selection that work in the country
            if charity_data.aggregate and charity_data.aggregate.areas:
                country.count = sum(
                    [
                        bucket.count
                        for bucket in charity_data.aggregate.areas
                        if bucket.key == country.iso2
                    ]
                )

        iati_data = fetch_iati(area.countries)

    if filetype == "json":
        inserts = {
            "selected-filters": render_template(
                "_data_selected_filters.html.j2", filters=filters_raw, area=area
            ),
            "example-charities": render_template(
                "_data_example_charities.html.j2",
                data=charity_data,
                area=area,
                all_charity_data=fetch_all_charities(),
            ),
            "charity-count": "{:,.0f} UK NGO{}".format(
                charity_data.count, "" if charity_data.count == 1 else "s"
            ),
            "word-cloud": render_template(
                "_data_word_cloud.html.j2", data=charity_data
            ),
            "max-countries-header": "{:,.0f}".format(filters.max_countries),
        }

        if page == "show-charities":
            inserts["data-list"] = render_template(
                "_data_list_table.html.j2",
                pages=pages,
                active_page="show-charities",
                filters=filters_raw,
                data=charity_data,
                area=area,
            )

        return jsonify(
            dict(
                area=area,
                inserts=inserts,
                charts=charity_data.get_charts(),
                filters=filters_raw,
                pages=pages,
            )
        )

    return render_template(
        pages[page]["template"],
        area=area,
        data=charity_data,
        iati_data=iati_data,
        filters=filters_raw,
        pages=pages,
        region_type=url_base[1].get("regiontype"),
        api_url=pages[page]["api_url"],
    )


@bp.route("/charity/<charityid>")
def charity(charityid: str) -> tuple[str, int] | str | Response:
    charity_data = fetch_charity_details(ids=[charityid], all_finances=True)

    if charity_data.count == 0:
        return (
            render_template(
                "404.html.j2",
                lookingfor=_(
                    'Charity "%(charityid)s" could not be found', charityid=charityid
                ),
            ),
            404,
        )

    char = charity_data.get_charity()
    if not isinstance(char, Charity):
        return (
            render_template(
                "404.html.j2",
                lookingfor=_(
                    'Charity "%(charityid)s" could not be found', charityid=charityid
                ),
            ),
            404,
        )
    char.iati = fetch_iati_by_charity(getattr(char, "orgIds"))

    return render_template("charity.html.j2", data=char)

ngo_explorer/blueprints/home.py
from flask import Blueprint, render_template

bp = Blueprint("home", __name__, url_prefix="/")


@bp.route("/")
def index():
    return render_template("index.html.j2")


@bp.route("/about")
def about():
    return render_template("about.html.j2")

ngo_explorer/blueprints/upload.py
import os
import pickle
import re
import uuid
from typing import Optional

from flask import (
    Blueprint,
    abort,
    current_app,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_babel import _

from ngo_explorer.blueprints.data import data_page
from ngo_explorer.classes.countries import CountryGroupItemUpload

bp = Blueprint("upload", __name__, url_prefix="/upload")


@bp.route("/")
def data():
    return render_template("upload.html.j2")


@bp.route("/", methods=["POST"])
def process_data():
    charitynumbers_raw: Optional[str] = request.values.get("charitynumbers")
    if not charitynumbers_raw:
        abort(400)

    charitynumbers = re.split(r"\W+", charitynumbers_raw)
    charitynumbers = set(charitynumbers)
    charitynumbers = sorted([c.strip() for c in charitynumbers if isinstance(c, str)])

    # charity_data = fetch_charity_details(ids=charitynumbers)

    list_id = str(uuid.uuid4())

    title = request.values.get("upload-name")

    with open(
        os.path.join(current_app.config["DATA_CONTAINER"], "{}.pkl".format(list_id)),
        "wb",
    ) as a:
        pickle.dump(
            dict(
                title=title,
                charitynumbers=charitynumbers,
                # data=charity_data,
            ),
            a,
        )

    return redirect(url_for(".fetch_uploaded_data", fileid=list_id), code=303)


def upload_pages(fileid):
    return {
        "dashboard": {
            "name": _("Dashboard"),
            "url": url_for(".fetch_uploaded_data", fileid=fileid),
        },
        "show-charities": {
            "name": _("Show NGOs"),
            "url": url_for(".list_uploaded_data", fileid=fileid),
        },
        "download": {
            "name": _("Download"),
            "url": url_for(".download_uploaded_data", fileid=fileid),
        },
    }


@bp.route("/<fileid>/<subpage>.<filetype>", methods=["GET", "POST"])
@bp.route("/<fileid>.<filetype>", methods=["GET", "POST"])
@bp.route("/<fileid>/<subpage>")
@bp.route("/<fileid>")
def fetch_uploaded_data(fileid, filetype="html", subpage="dashboard"):
    if subpage not in ["dashboard", "show-charities", "download"]:
        return render_template("404.html.j2"), 404

    filepath = os.path.join(
        current_app.config["DATA_CONTAINER"], "{}.pkl".format(fileid)
    )

    if not os.path.exists(filepath):
        return (
            render_template(
                "404.html.j2",
                lookingfor=_('File "%(fileid)s" could not be found', fileid=fileid),
            ),
            404,
        )

    with open(filepath, "rb") as a:
        data = pickle.load(a)

    return data_page(
        area=CountryGroupItemUpload(
            name=data["title"] if data["title"] else "Data upload",
            type_="upload",
        ),
        charity_ids=data["charitynumbers"],
        filetype=filetype,
        page=subpage,
        url_base=["upload.fetch_uploaded_data", {"fileid": fileid}],
    )

ngo_explorer/templates/404.html.j2
{% extends "index.html.j2" %}

{% block title %}{% trans %}Not found{% endtrans %} | NGO Explorer{% endblock %}

{% block message %}
<div class="w-100 mv3 ba bw2 b--dark-red">
    <h2 class="korolev lh-title ma0 bg-dark-red white pa1">{% trans %}Not found{% endtrans %}</h2>
    {% if lookingfor %}
    <div class="pa2">
        <p class="lh-title ma0 gray">{{ lookingfor }}</p>
    </div>
    {% endif %}
</div>
{% endblock %}

ngo_explorer/templates/_data_iati.html.j2
<div class="w-100 cf mt2" id="iati">
    <div class="cf">
        <div class="db fl w-30-l w-100 mh0 mv2 pr3">            
            <h3 class="korolev b lh-title pa0 ma0 tr-l">{% trans %}IATI Activity data{% endtrans %}</h3>
            <p class="lh-copy gray f6 tr-l mw5-l fr-l">
                {% trans %}
                <abbr title="International Aid Transparency Iniative">IATI</abbr> is a global initiative to improve the transparency of 
                development and humanitarian resources and their results to address poverty and crises. The data presented here is
                sourced from <a href="https://www.oipa.nl/home" class="link blue external-link" target="_blank">OIPA</a>.
                {% endtrans %}
            </p>
        </div>
        <div class="db fl w-50-l w-100 mh0 mv2">
            <p class="lh-copy pa0 ma0">
                {% if area.countries|length > 5 %}
                {% trans %}
                Select a country below to see a list of UK-registered organisations operating in 
                these countries, sourced from data published by IATI publishers.
                {% endtrans %}
                {% elif area.countries|length > 1 %}
                {% trans %}
                List of UK-registered organisations operating in these countries,
                sourced from data published by IATI publishers.
                {% endtrans %}
                {% else %}
                {% trans countryname=area.countries|map(attribute="name")|first %}
                List of UK-registered organisations operating in {{ countryname }},
                sourced from data published by IATI publishers.
                {% endtrans %}
                {% endif %}
            </p>
        {% if area.countries|length > 5 %}
            <ul class="list pa0 ma0">
                {% for c in area.countries if iati_data.get(c["iso2"], []) %}
                <li class="dib mr2 pb0">
                    <a href="{{ url_for('data.country', countryid=c.iso.lower()) }}#iati"
                        class="link blue mw5 nowrap dib overflow-hidden truncate v-mid">
                        {{ c.name }}
                    </a>
                    <span class="dib mw5 nowrap dib overflow-hidden truncate f7 gray v-mid">
                        [{{ iati_data.get(c["iso2"], [])|length }}{% if loop.first %} {{ ngettext("organisation", "organisations", iati_data.get(c["iso2"], [])|length)}}{% endif %}]
                    </span>
                </li>
                {% endfor %}
            </ul>
        {% else %}
            {% for c in area.countries if iati_data.get(c["iso2"], []) %}
            {% if area.countries|length > 1 %}
            <p class="b">{{ c["name"] }}</p>
            {% endif %}
            <ul class="list pa0 ma0">
                {% for r in iati_data.get(c.iso2, [])|sort(attribute='count', reverse=True) if r.name %}
                <li class="dib mr2 pb0">
                    <a href="https://d-portal.org/ctrack.html?publisher={{ r.ref }}#view=list_transactions&country_code={{ c.iso2 }}" target="_blank" 
                        class="link blue mw5 nowrap dib overflow-hidden truncate v-mid">
                        {{ r.name }}
                    </a>
                    <span class="dib mw5 nowrap dib overflow-hidden truncate f7 gray v-mid">
                        [{{r.count}}]
                    </span>
                </li>
                {% endfor %}
            </ul>
            {% endfor %}
        {% endif %}
            {% if area.countries|length == 1 %}
            <h3 class="korolev mh0 mt3 mb0 pa0">
                <a href="https://d-portal.org/ctrack.html?country={{ area.countries|map(attribute='iso2')|join(",") }}#view=main"
                    target="_blank" class="normal link b dark-gray external-link">
                    {% trans countryname=area.countries|map(attribute="name")|first %}
                    Data on {{ countryname }} from IATI d-portal{% endtrans %}
                </a>
            </h3>
            <iframe scrolling="no"
                src="https://d-portal.org/ctrack.html?flava=original&rgba=inspire&country={{ area.countries[0].iso2 }}&#view=frame&frame=stats&size=640"
                style="height: 304px;"
                class="w-100"
                frameborder="0"></iframe>
            {% elif area.countries|length < 20 %}
            <h3 class="korolev mh0 mt3 mb0 pa0">
                <a href="https://d-portal.org/ctrack.html?country={{ area.countries|map(attribute='iso2')|join(",") }}#view=main"
                    target="_blank" class="link blue f5 normal external-link">
                    {% trans %}Find more data on IATI d-portal{% endtrans %}
                </a>
            </h3>
            {% else %}
            <h3 class="korolev mh0 mt3 mb0 pa0">
                <a href="https://d-portal.org/"
                    target="_blank" class="link blue f5 normal external-link">
                    {% trans %}Find more data on IATI d-portal{% endtrans %}
                </a>
            </h3>
            {% endif %}
        </div>
    </div>
</div>

ngo_explorer/templates/_data_word_cloud.html.j2
{% if data.charts.word_cloud %}
<div>
    <p>{% trans %}Most common words from the description of a random set of 30 NGOs matching your search.{% endtrans %}</p>
    <ul class="list ma0 pa0">
        {% set max_count = data.charts.word_cloud.values()|list|first %}
        {% set min_count = data.charts.word_cloud.values()|list|last %}
        {% set scaling = 50 if max_count > min_count else 20 %}
        {% for word, count in data.charts.word_cloud.items() %}
        <li class="dib ma0 pa0">
            <a class="{{ loop.cycle('green b', 'dark-green') }} link dim word-cloud-word"
               style="font-size: {{ ((count / max_count) * scaling) + 10 }}px;"
               href="#">
                {{ word }}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

ngo_explorer/templates/_header.html.j2
<header class="bg-light-gray">
    <div class="ph3-ns ph2 mw9 center pv3 mb4-l mb2 cf flex-l items-center justify-between">
        <div class="fl w-50-l w-100 mt2">
            <h1 class="korolev ma0 ttu f1">
                <a class="link dark-gray b ttl ma0" href="{{ url_for('home.index') }}">
                    <img src="{{ url_for('static', filename='images/ngo_explorer_logo.svg') }}"
                        class="header-logo ma3 ma0-ns"
                        alt="NGO Explorer - {{ _('Building networks across development NGOs') }}" />
                </a>
            </h1>
        </div>
        <nav class="fr-ns fl w-50-l w-100 cf">
            <ul class="list ma0 pa0 fr f4-l f5 korolev">
                <li class="dib b ml3"><a class="link darken dark-green" href="{{ url_for('home.index') }}">{% trans %}Home{% endtrans %}</a></li>
                <li class="dib b ml3"><a class="link darken dark-green" href="{{ url_for('home.about') }}">{% trans %}About{% endtrans %}</a></li>
                <li class="dib b ml3"><a class="link darken dark-green" href="{{ url_for('upload.data') }}">{% trans %}Upload{% endtrans %}</a></li>
            </ul>
        </nav>
    </div>
</header>

ngo_explorer/templates/_upload_data_header.html.j2
{% import "_tabs.html.j2" as tabs %}
<div class="page-header mb4 w-100 cf">
    <div class="flex flex-column items-center tc">
        {{ data.countries|location_map() }}
        {% if area.name %}
        <h2 class="korolev lh-title mb0 mt3">{{ area.name }}</h2>
        <p class="korolev f4 gray lh-copy mv0">
        {% trans count=data.count, ccount=data.count|_n %}
        Data on {{ ccount }} charity
        {% pluralize %}
        Data on {{ ccount }} charities
        {% endtrans %}
        </p>
        {% else %}
        <h2 class="korolev lh-title mb0 mt3">
        {% trans count=data.count, ccount=data.count|_n %}
        Data on {{ ccount }} charity
        {% pluralize %}
        Data on {{ ccount }} charities
        {% endtrans %}
        </h2>
        {% endif %}
        <p class="lh-copy mv2 pa0 f6 gray mw6">
            {% trans %}Figures refer to charities registered with the Charity Commission for England and Wales,
            based on a selection of charities uploaded by a user.{% endtrans %}
        <p>
        {{ tabs.tabs(active_page, pages) }}
    </div>
</div>

ngo_explorer/templates/data-show-charities.html.j2
{% extends "data.html.j2" %}

{% block content %}
{% set active_page = "show-charities" %}
{% if area.type_=="upload" %}
{% include '_upload_data_header.html.j2' %}
{% else %}
{% include '_data_header.html.j2' %}
{% endif %}
<form action="{{request.path}}" id="filter-form">
    {% include '_data_sidebar.html.j2' %}
</form>

<div class="fl w-100 w-70-l">
    <div class="mb4" id="data-list">
        {% include '_data_list_table.html.j2' %}
    </div>
</div>
{% endblock %}

ngo_explorer/templates/index.html.j2
{% extends "base.html.j2" %}

{% block title %}NGO Explorer{% endblock %}

{% block content %}
<div class="fl w-70-l w-100">
    <div class="cf lh-copy">
        <div class="db fl w-30-l w-100 ma0 tr-l pr3 b">&nbsp;</div>
        <div class="db fl w-70-l w-100 ma0">
            <h2 class="korolev ma0 mv2-l">{% trans %}Explore UK charities working across the world{% endtrans %}</h2>
            {% block message %}{% endblock %}
            <form action="{{ url_for('data.country', **{'countryid': 'all'}) }}">
                <div class="mb1 bb bw2 b--mid-gray w-100 flex items-center">
                    <i class="material-icons">search</i>
                    <input id="filter-country-list" name="filter-search"
                        class="w-100 lh-copy bn bg-inherit pa2 border-box"
                        placeholder="{{ _('Type to search (try a country)') }}" value="" autocomplete="off" />
                </div>
            </form>
        </div>
    </div>
    <div class="" id="country-list">
        {% for country_group in countries %}
        <div class="cf country-group lh-copy {% if country_group.show_initial %}db{% else %}dn{% endif %}"
            data-initialclass="{% if country_group.show_initial %}db{% else %}dn{% endif %}">
            <div class="db fl w-30-l w-100 mh0 mv2 tr-l pr3 b">
                {% if country_group.title and country_group.title.lower() in config.PLOTLY_GEO_SCOPES %}
                <div class="w-100 fr country-group-name">
                    {{ country_group.title or "&nbsp;" }}
                </div>
                <div class="w-50 fr dn db-l">
                    {{ []|location_map(continents=[country_group.title.lower()], height=120, landcolor='#666', static=True) }}
                </div>
                {% else %}
                <div class="country-group-name">{{ country_group.title or "&nbsp;" }}</div>
                {% endif %}
            </div>
            <div class="db fl w-70-l w-100 mh0 mv2 country-group-list">
                <ul class="list pa0 ma0">
                    {% for c in country_group.values|sort(attribute="name") %}
                    <li class="dib mr2 pb0">
                        <a href="{{ c.id }}" class="link blue">{{ c.name|first_upper }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endfor %}
        {% for group in [("causes", _("What the charity does")), ("beneficiaries", _("Who the charity works with")), ("operations", _("How the charity works"))] %}
        <div class="cf country-group lh-copy dn" data-initialclass="dn">
            <div class="db fl w-30-l w-100 mh0 mv2 tr-l pr3 b">
                <div class="country-group-name">{{ group[1] }}</div>
            </div>
            <div class="db fl w-70-l w-100 mh0 mv2 country-group-list">
                <ul class="list pa0 ma0">
                    {% for code, name in classification[group[0]].items() %}
                    <li class="dib mr2 pb0">
                        <a href="{{ url_for('data.country', **{'countryid': 'all', 'filter-classification': code}) }}"
                            class="link blue">{{ name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endfor %}
        <div class="cf country-group lh-copy">
            <div class="db fl w-30-l w-100 mh0 mv2 tr-l pr3 b">
                <div class="country-group-name">
                    {% trans %}UK headquarters{% endtrans %}
                </div>
            </div>
            <div class="db fl w-70-l w-100 mh0 mv2 country-group-list">
                <ul class="list pa0 ma0">
                    {% for code, name in regions.items() %}
                    <li class="dib mr2 pb0">
                        <a href="{{ url_for('data.country', **{'countryid': 'all', 'filter-regions': code}) }}"
                            class="link blue">{{ name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="cf country-group lh-copy">
            <div class="db fl w-30-l w-100 mh0 mv2 tr-l pr3 b">
                <div class="country-group-name">{% trans %}Example searches{% endtrans %}</div>
            </div>
            <div class="db fl w-70-l w-100 mh0 mv2 country-group-list">
                <ul class="list pa0 ma0">
                    {% for q in ["agriculture", '"children" and "youth"', "poverty", "education", "conservation", "entrepreneurship", "sanitation"] %}
                    <li class="dib mr2 pb0">
                        <a href="{{ url_for('data.country', **{'countryid': 'all', 'filter-search': q}) }}"
                            class="link blue">
                            {{ q }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="cf country-group lh-copy dn" data-initialclass="dn">
            <div class="db fl w-30-l w-100 mh0 mv2 tr-l pr3 b">
                <div class="country-group-name">{% trans %}Search{% endtrans %}</div>
            </div>
            <div class="db fl w-70-l w-100 mh0 mv2 country-group-list">
                <ul class="list pa0 ma0">
                    <li class="dib mr2 pb0">
                        <a href="#" data-baseurl="{{ url_for('data.country', **{'countryid': 'all'}) }}"
                            class="link blue" id="search-link">
                            "<span id='search-term'></span>" {% trans %}in charity description{% endtrans %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        <div class="db fl w-30-l w-100">&nbsp;</div>
        <div class="db fl w-70-l w-100 mt4-l">
            <div class="cf br2 bg-light-gray pa3">
                <h3 class="korolev ma0">{% trans %}Upload your own data{% endtrans %}</h3>
                <div class="cf mt2">
                    <a href="{{ url_for('upload.data') }}"
                        class="korolev ph4 pv3 bg-yellow dark-gray no-underline dib f5 br2 fr darken ml2">{% trans %}Upload
                        your data{% endtrans %} <i class="material-icons v-mid">publish</i></a>
                    <p class="ma0 pa0">
                        {% trans %}If you have a list of England and Wales charity numbers, you can
                        upload your data to explore your group of
                        charities.{% endtrans %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fl w-30-l w-100">

    <div class="ml3-l ml0 br2 bg-light-gray pa3">
        <h3 class="korolev ma0">{% trans %}About this site{% endtrans %}</h3>
        <div class="cf">
            <p>
                {% trans %}This tool uses data from
                <a href="https://findthatcharity.uk/" class="link blue" target="_blank">Find that Charity</a>
                to explore the work of English and Welsh charities in other countries.{% endtrans %}
            </p>
            <p>
                {% trans about_page=url_for('home.about') %}Charities working only in the UK are excluded.
                A number of good sites already exist for charities which work only
                in the UK and these are listed on <a href="{{ about_page }}#resources" class="link blue">the network
                    page</a>.{% endtrans %}
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock %}